### ISSUE TITLE
Running problem

### ISSUE THREAD

**Issue by alleykk** [SeUniVr/RestTestGen#10]
Hello,

I have cloned the RTG, I opened it via IntelliJ IDE (on windows) and ran the io.resttestgen.core.cli.App.
But I got error!
How should I solve and run the RTG?

Many thanks in advance.

![321](https://user-images.githubusercontent.com/130459453/231140015-2e4069bf-3408-4c3b-bda6-581b9bfc95b2.PNG)

**Comment by davidecorradini** [comment]
Hello,

I can see form the log that the request was not processed by the server because a connectivity problem. Is the REST API under test up and running, and reachable trough the network? Make sure to specify the correct URL of the API in the specificaiton.

Best,
Davide

**Comment by alleykk** [comment]
I've cloned and ran the RTG!
Should I change anything? Actually I didn't make change in the specification, because I don't know how should I change and input URLs!
Where should I change the URL of API?
Please help me to run RTG for an API!

**Comment by davidecorradini** [comment]
Please let me know what do you want to do with RTG so I can help you with a custom configuration

**Comment by alleykk** [comment]
I want to test a sample API.
I need an API to test with both strategies.

**Comment by davidecorradini** [comment]
In the June release (v23.06) that is scheduled for next week, the README file will explain everything about your concern. Thank you for your patience.
Davide

**Comment by davidecorradini** [comment]
Hello, please let me know if the new README file was able to guide you. Thanks!

**Comment by davidecorradini** [comment]
Closed because of user inactivity
