### ISSUE TITLE
It seems that RestTestGen will never update Authorization token？

### ISSUE THREAD

**Issue by LJianCode** [SeUniVr/RestTestGen#11]
I am using RestTestGen, and I read some code, I found it will never update Authorization token. Is it a bug?

**Comment by davidecorradini** [comment]
Hello,

We acknowledge that RestTestGen is currently not updating the token. We intend to resolve this issue in the upcoming release, which is scheduled for June, just a few days away. We appreciate your patience.

Thank you.

Davide

**Comment by LJianCode** [comment]
Got it! Thanks

**Comment by davidecorradini** [comment]
I am pleased to inform you that the latest version of RestTestGen has been enhanced to include token refreshing functionality. With this improvement, any token-related issues should be resolved. If you encounter any unexpected behaviors regarding tokens, please feel free to reopen this issue for further investigation. Thank you!
