### ISSUE TITLE
Unable to start using docker

### ISSUE THREAD

**Issue by henning410** [SeUniVr/RestTestGen#18]
Follow your Readme, when running the command `docker run -v ./:/app --network="host" rtg` I get the error: 

`docker: Error response from daemon: create ./: "./" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

I think, the directory of -v option should be the directory of RestTestGen? So I tried instead `docker run -v /home/user/Desktop/RestTestGen --network="host" rtg` but I get the error: 

```
FAILURE: Build failed with an exception.

* What went wrong:
Directory '/app' does not contain a Gradle build.
```

How can I run RestTestGen correctly using docker?

**Comment by davidecorradini** [comment]
Hello,

I just tried to run RTG within Docker myself, and it started correctly.

Have you run both the build and run commands? From the main directory?

Also, I see that the error is related to the string "./". It may depend on your operating system. What OS are you using? (I only tested the script in Ubuntu).

Best,
Davide

**Comment by henning410** [comment]
The build command `docker build -t rtg .` worked, yes.

I'm using Kali Linux

**Comment by davidecorradini** [comment]
This is (hopefully) fixed version of the command you tries, with absolute path do the RTG folder. I added `:/app` to map the RTG folder on your system to the /app folder in the docker container.
```docker run -v /home/user/Desktop/RestTestGen:/app --network="host" rtg```
Let me know if this works!
Best,
Davide

**Comment by henning410** [comment]
This works perfectly, thank you very much for your quick help :)
