### ISSUE TITLE
HTTPS and HTTP/2 support?

### ISSUE THREAD

**Issue by henning410** [SeUniVr/RestTestGen#24]
Hey Davide, 

I just want to make sure I'm not missing anything. Currently HTTPS and HTTP/2 are not supported, right? 

Best regards
Henning

**Comment by davidecorradini** [comment]
Hey Henning,

The HTTP client of RestTestGen is just a simple OkHttp client, so it has all the features of OkHttp.

HTTPS is definitely supported! I used it successfully in the past. FYI, I set the OkHttp client to trust all certificates (including those not emitted by a recognized certification authority), as RestTestGen is often used in development contexts where certificates are self-signed. For further information about this, please see the constructor of the `TestRunner` class.

**Comment by henning410** [comment]
Oh, you are absolutely right. Maybe next time I'll try it before I ask :D 
I just tested it on some API with HTTPS and HTTP/2 and RestTestGen works great!

Thanks

**Comment by davidecorradini** [comment]
That's great. No worries. Get in touch anytime!
