### ISSUE TITLE
Request execution failed: connectivity problem or timeout

### ISSUE THREAD

**Issue by mo718** [SeUniVr/RestTestGen#5]
Hello,when I run RestTestGen in IDEA, I can build odg.dot, but can not generate valid http requests. Why?
![image](https://user-images.githubusercontent.com/64512529/199213343-baec69dc-67eb-438d-adf0-7c4277ac7970.png)
My REST API does not require permission authentication.This is file rtg_config.json and swagger.json
![image](https://user-images.githubusercontent.com/64512529/199213853-d894bb65-7b5a-46f8-a2db-6c34d3df6c17.png)
![image](https://user-images.githubusercontent.com/64512529/199214095-eb4ece58-eb10-4827-9c38-21f88d049970.png)

**Comment by davidecorradini** [comment]
Hello,
the "Request execution failed" message is typically triggered when the REST API under test is not reachable, or it responds by closing the HTTP connection.
Are you able to reach the API at the same URL from Postman?
Also, are you sure your local API is using HTTPS and not HTTP? I can see HTTPS in the server URL, but, typically, locally deployed REST APIs do not require SSL/TLS.

**Comment by mo718** [comment]
Thank you

**Comment by davidecorradini** [comment]
It is working? What was the problem? Can I close the issue?
Thanks
Davide

**Comment by mo718** [comment]
My local API is using HTTP and not HTTPs. I modified the file swagger.json and it can work. Thanks for your help, you can close this issue.

**Comment by davidecorradini** [comment]
Thank you for your feedback
