### ISSUE TITLE
Authorization problem

### ISSUE THREAD

**Issue by mo718** [SeUniVr/RestTestGen#8]
when I testing Authorization service,it reports this error:
![image](https://user-images.githubusercontent.com/64512529/223104540-565a88ef-6e01-49dc-b7bc-79ee82bf10b9.png)
my auth.py is
![image](https://user-images.githubusercontent.com/64512529/223105740-7298bb65-19b6-4df4-99da-6d213403e4e4.png)

the rtg_config.json is
![image](https://user-images.githubusercontent.com/64512529/223104959-44a28ba2-988b-41af-9311-f9474172a5fd.png)

**Comment by davidecorradini** [comment]
Hello, the output of the script should be a JSON. In your case, I think you just put JSON data in a .py file.
To fix this you could:
- completely remove the authCommand line from the `rtg_config.json` file, in case your API does not require authentication
- change the authCommand to `cat auth.py` (or Windows equivalent command) to make the command print out the content of the file
- change your python script to print out JSON

Please let me know if you managed to run the code.
